# Generated by Django 4.1.4 on 2022-12-29 22:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserORM",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=256, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="TagORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "tag",
                "db_table": "tag",
            },
        ),
        migrations.CreateModel(
            name="PollORM",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=256, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.CharField(max_length=128)),
                ("tags", models.ManyToManyField(related_name="polls", to="orm.tagorm")),
            ],
            options={
                "verbose_name": "poll",
                "db_table": "poll",
            },
        ),
        migrations.CreateModel(
            name="AnswerORM",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=256, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.CharField(max_length=128)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="orm.pollorm",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer",
                "db_table": "answer",
            },
        ),
    ]
